yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Изображение',
        help_text='Изображение для поста',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )

    class Meta:
        ordering = ('-pub_date',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        null=True
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='follow_constraints')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


def paginator(request, posts):
    paginator = Paginator(posts, settings.POST_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    post_list = Post.objects.all()
    context = {
        'page_obj': paginator(request, post_list)
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': paginator(request, posts),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user_obj = get_object_or_404(User, username=username)
    user_posts = user_obj.posts.all()
    posts_number = user_posts.count()
    current_user = request.user
    if current_user.is_authenticated:
        following = user_obj.following.filter(user=current_user.id).exists()
    else:
        following = None
    context = {
        'page_obj': paginator(request, user_posts),
        'user_obj': user_obj,
        'posts_number': posts_number,
        'following': following,
        'current_user': current_user
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    comments = post_obj.comments.all()
    form = CommentForm(request.POST or None,)
    context = {
        'post_obj': post_obj,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user.username)
    form = PostForm()
    context = {'form': form}
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    if post_obj.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_obj,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'post_obj': post_obj}
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post_obj
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user
    )
    context = {
        'page_obj': paginator(request, post_list)
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            author=author,
            user=request.user
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow_obj = Follow.objects.filter(
        user=request.user.id, author=author.id
    )
    if request.user != author and follow_obj.exists():
        follow_obj.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% block title %}
    Последние обновления избраных авторов
  {% endblock %}
  {% block content %}   
    <h1>Последние обновления избраных авторов</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% if not forloop.last %}        
    <hr>
    {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
    {{ group.title }}
  {% endblock %}
  {% block content %}
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    <hr></hr>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}        
      <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block title %}
    Последние обновления на сайте
  {% endblock %}
  {% block content %}   
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' %}
    {% load cache %}
    {% cache 20 index_page user.username page_obj.number follow %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% if not forloop.last %}        
    <hr>
    {% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if post_obj %}
    Редактировать пост
  {% else %}
    Добавить пост
  {% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post_obj %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}                    
          </div>
          <div class="card-body">
            {% load user_filters %}
              {% if form.errors %}
                {% for field in form %} 
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              {% if post_obj %}
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_obj.pk %}">
              {% else %}
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
              {% endif %}
              {% csrf_token %}
            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  {{ form.text.label }}                  
                  <span class="required text-danger" >*</span>                  
                </label>
                {{ form.text }}                
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  {{ form.group.label }}                  
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  {{ form.image.label }}                      
                </label>
                {{ form.image }}
                <small id="id_image-help" class="form-text text-muted">
                  {{ form.image.help_text }}
                </small>                     
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post_obj %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}               
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
  {% block title %}
  Пост {{ post_obj.text | truncatewords:30 }} 
  {% endblock %}
  {% block content %}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post_obj.pub_date | date:"j F Y" }} 
          </li>
          {% if post_obj.group.slug is not None %}   
          <li class="list-group-item">
            Группа: {{ post_obj.group.title }}
            <a href="{% url 'posts:group_list' post_obj.group.slug %}">
              <br>Все записи группы
            </a>
          </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post_obj.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_obj.author.posts.all.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post_obj.author.username %}">
              Все посты пользователя
            </a>
          </li>
          {% if user.is_authenticated %}
            {% if post_obj.author == user %}
              <li class="list-group-item">
                <a href="{% url 'posts:post_edit' post_obj.pk %}">
                  Редактировать пост
                </a>
            {% endif %}
          {% endif %}
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% load thumbnail %}
        {% thumbnail post_obj.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
         {{ post_obj.text }}
        </p>
      </article>
    </div>
    {% include 'includes/comment_form.html' %} 
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  {% block title %}
  Профайл пользователя {{ user_obj.get_full_name }} 
  {% endblock %}
  {% block content %}
    <div class="container py-5">        
      <h1>Все посты пользователя {{ user_obj.get_full_name }} </h1>
      <h3>Всего постов: {{ posts_number }} </h3>
      {% if current_user.is_authenticated %}
        {% if current_user != user_obj %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' user_obj.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' user_obj.username %}" role="button"
              >
                Подписаться
              </a>
          {% endif %}
        {% endif %}
      {% endif %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}      
      {% if not forloop.last %}        
      <hr>
      {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}  
    </div>
  {% endblock %}